apiVersion: v1
kind: Secret
metadata:
  name: terraboard-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID:  {{ printf .Values.secrets.aws_key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY:  {{ printf .Values.secrets.aws_secret_key | b64enc | quote }}
  DB_PASSWORD:  {{ printf .Values.secrets.db_pass | b64enc | quote }}
  POSTGRESQL_PASSWORD:  {{ printf .Values.secrets.db_pass | b64enc | quote }}



  